# Generated by Django 2.2.16 on 2023-03-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230320_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, upload_to='recipes/'),
            preserve_default=False,
        ),
    ]
